version: 2
updates:
- package-ecosystem: nuget
  directory: /src/DotNetHelloWorld.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  groups:
    production-dependencies:
      dependency-type: "production"
      patterns: "*"
- package-ecosystem: nuget
  directory: /src/DotNetHelloWorld.Web/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
